<a href="https://colab.research.google.com/github/vyspriyL/adhoc-notes-daily-basis-/blob/master/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow

In [3]:
!pip3 list | grep -i tensorflow

mesh-tensorflow          0.0.5                
tensorflow               1.14.0               
tensorflow-estimator     1.14.0               
tensorflow-hub           0.4.0                
tensorflow-metadata      0.13.0               
tensorflow-probability   0.7.0                


In [0]:
import tensorflow as tf

In [0]:
#to assign fixed value in tensorflow we need to define constant 
x=tf.constant([30])



In [0]:
#more than one value
#multi value constant 
x1=tf.constant([3,5,77,88])

In [8]:
type(x1)

tensorflow.python.framework.ops.Tensor

In [0]:
y=tf.constant(20)

In [0]:
#equation
Z=x+y  #new tensor ---Z equation compile and wait to
# cpu,gpu,tpu --


In [13]:
Z

<tf.Tensor 'add_1:0' shape=(1,) dtype=int32>

In [14]:
type(Z)

tensorflow.python.framework.ops.Tensor

In [0]:
# we another method to add the same
z1=tf.add(x,y)

In [0]:
# now time for assigning resources to our eq.
sess=tf.Session()  #connect cpu,gpu,tpu

In [0]:
# now we can run our eq.
output=sess.run(Z)

In [20]:
output

array([50], dtype=int32)

In [0]:
# closing session
sess.close()

In [0]:
# we can perform same task in another  way where we dont want to close session
with tf.Session() as sess:
  output1=sess.run(Z)

In [24]:
output


array([50], dtype=int32)

**Placeholder
**

In [0]:
#first place holder
p1=tf.placeholder(tf.int32)

In [0]:
# placeholder 2
p2=tf.placeholder(tf.int32)

In [0]:
# adding values
sum=tf.add(p1,p2)

In [0]:
# general
sum1=p1+p2

In [0]:
# time for creating session
with tf.Session() as sess:
  output2=sess.run(sum1,{p1:[3,6],p2:[5,8]})

In [31]:
output2

array([ 8, 14], dtype=int32)